name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: >
        sudo apt-get update &&
        sudo apt-get install -y --no-install-recommends
        build-essential
        libcriterion-dev
        libjansson-dev
    - name: Run configure script
      run: ./configure
    - name: Build and test the program
      run: make test
    - name: Build and test the program variant for the alphabet '0123456789'
      run: make test
