name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: >
        sudo apt-get update &&
        sudo apt-get install -y --no-install-recommends
        build-essential
        libcriterion-dev
        libjansson-dev
    - name: configure
      run: ./configure
    - name: make test
      run: make test
    - name: make test ALPHABET=0123456789
      run: make test
